spring.application.name=chit-fund
spring.profiles.active=local
spring.datasource.url=jdbc:mysql://localhost:3306/chitfund?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Dev6339!
#spring.datasource.password=Dev6339! //for MAC
#spring.datasource.password=root// for VAM
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
server.port=8000


# JWT Secret (store securely in prod!)
jwt.secret=9f3c7a2d4e8b1c6f0a5d9e3b7c2f1a6d4b8e0c3f7a1d9b6e2c5f8a0b3d7e1c4
jwt.expiration=86400000